version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      # 从.env文件加载其他环境变量
    env_file:
      - .env
    volumes:
      # 持久化数据库文件
      - app_data:/app/data
      # 持久化上传文件（如果有）
      - app_uploads:/app/public/uploads
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - db-init

  # 数据库初始化服务
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/prod.db
    env_file:
      - .env
    command: ["sh", "-c", "npx prisma generate && npx prisma db push && echo 'Database initialized'"]
    restart: "no"

volumes:
  app_data:
    driver: local
  app_uploads:
    driver: local